# Generated by Django 3.2.5 on 2021-08-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_news_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image_eight',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image_five',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image_four',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image_nine',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image_one',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image_seven',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image_six',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image_three',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image_two',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
