# Generated by Django 3.2.5 on 2021-08-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20210823_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image_five',
            field=models.ImageField(upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image_four',
            field=models.ImageField(upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image_three',
            field=models.ImageField(upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image_two',
            field=models.ImageField(upload_to='media/images/'),
        ),
    ]
